### ISSUE TITLE
What does "Container action is only supported on Linux" mean?

### ISSUE THREAD

**Issue by dnedrow** [chuhlomin/render-template#18]
Given the error "Container action is only supported on Linux", I'm guessing this action won't work on a macOS runner?

Below is what I'm attempting. Should this work on a macOS runner? I'm not sure if I've just configured something wrong, or was expecting too much from the action.

```markdown
#Test Template

Use the link(s) below to download artifacts created by this build.
  
* {{ .foourl | mdlink "Foo Artifact" }}
* {{ .barurl | mdlink "Bar Artifact" }}
```

```yaml
      - name: Render template
        id: artifact-template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/ACTION_TEMPLATES/artifact-download-template.md
          vars: |
            foourl: ${{ steps.artifact-upload-step-foo.outputs.artifact-url }}
            barurl: ${{ steps.artifact-upload-step-bar.outputs.artifact-url }}
```

**Comment by dnedrow** [comment]
OK, looking at the sources, it would appear this action will only work in a linux-runner workflow, so no macOS or Windows support. I can only surmise that this is due to this having been written in Go.

It would be nice if this were clarified in the README so people don't waste their time with the action.

**Comment by chuhlomin** [comment]
Go supports cross-compilation for Windows and MacOS, so it should be possible.
The more significant limitation is that it is a Docker action.
It seems like Docker is unavailable on the Windows and Apple silicon GitHub Actions runner.
If that helps, I can distribute this action as a binary file compiled for the required architecture.
Added note to README about that

**Comment by rwaight** [comment]
@dnedrow were you able to get the action to work with MacOS runners?  It looks like Docker currently not work on macOS runners with ARM architecture, at least according to https://github.com/docker/actions-toolkit/issues/317

There are some other related comments about using docker with MacOS runners:
- https://github.com/actions/runner/issues/1456#issuecomment-1999400776
- https://github.com/actions/runner-images/issues/17#issuecomment-1537238473
- https://github.com/actions/runner-images/issues/2150#issuecomment-1242888565

**Comment by artur2281** [comment]
> Dado el error "La acc

**Comment by tooomm** [comment]
>The more significant limitation is that it is a Docker action.
It seems like Docker is unavailable on the Windows and Apple silicon GitHub Actions runner.

On the new `ubuntu-slim` runners which are not full VM's, but container themselves, there is no Docker support as well. @chuhlomin 

Se https://docs.github.com/en/actions/reference/runners/github-hosted-runners#single-cpu-runners
>The container for ubuntu-slim runners runs in unprivileged mode. This means that some operations requiring elevated privileges—such as mounting file systems, using **Docker-in-Docker**, or accessing low-level kernel features—are not supported.

Right at the beginning of the job it fails with:
```
Pull down action image 'chuhlomin/render-template:v1.10'
  /usr/bin/docker pull chuhlomin/render-template:v1.10
  failed to connect to the docker API at unix:///var/run/docker.sock; check if the path is correct and if the daemon is running: dial unix /var/run/docker.sock: connect: no such file or directory
  Warning: Docker pull failed with exit code 1, back off 5.963 seconds before retry.
  /usr/bin/docker pull chuhlomin/render-template:v1.10
  failed to connect to the docker API at unix:///var/run/docker.sock; check if the path is correct and if the daemon is running: dial unix /var/run/docker.sock: connect: no such file or directory
  Warning: Docker pull failed with exit code 1, back off 8.873 seconds before retry.
  /usr/bin/docker pull chuhlomin/render-template:v1.10
  failed to connect to the docker API at unix:///var/run/docker.sock; check if the path is correct and if the daemon is running: dial unix /var/run/docker.sock: connect: no such file or directory
Error: Docker pull failed with exit code 1
```

<br>

This runners are designed for simple executions around automations.
Usually that's where your render-template action would be used as well.

Is it possible to rework the action from a "Docker action"?

**Comment by chuhlomin** [comment]
This is now addressed in [v1.11](https://github.com/chuhlomin/render-template/releases/tag/v1.11) via a new binary action. Instead of `chuhlomin/render-template@v1`, try `chuhlomin/render-template/binary@v1.11`. It downloads a pre-compiled binary and works on Linux, macOS, and Windows runners with no Docker required.

**Comment by tooomm** [comment]
> This is now addressed in [v1.11](https://github.com/chuhlomin/render-template/releases/tag/v1.11) via a new binary action. Instead of `chuhlomin/render-template@v1`, try `chuhlomin/render-template/binary@v1.11`. It downloads a pre-compiled binary and works on Linux, macOS, and Windows runners with no Docker required.

Awesome, thanks for taking a look!
I was trying with `chuhlomin/render-template/binary@v1` to stay on the latest patches and upcoming fixes.
It's currently still failing with:
```
Download action repository 'chuhlomin/render-template@v1' (SHA:807354a04d9300c9c2ac177c0aa41556c92b3f75)
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' for action 'chuhlomin/render-template/binary@v1'.
```

The checksum indicates that it's still pointing to v1.10 right now.
It looks like you need to sign-off one last step in your release action: https://github.com/chuhlomin/render-template/actions/runs/24434938266

**Comment by chuhlomin** [comment]
v1 is now promoted to v1.11 - `chuhlomin/render-template/binary@v1` should work now

**Comment by tooomm** [comment]
The action is now properly downloaded and executed.

However, the `Render template` step exits with "no assets to download" on an ubuntu-slim runner still, see the action step with debug output enabled: 🤔  https://github.com/Cockatrice/Cockatrice/actions/runs/24437907788/job/71580447742

**Comment by chuhlomin** [comment]
Sorry for the hassle! The v1 tag now points to v1.12 which fixes the binary download for floating tags like @v1. Give it another try.

**Comment by tooomm** [comment]
No worries, happy to test and report back.
Glad you're looking into this and I do very much appreciate your quick replies and fixes. 👍

No issues so far, looks good when running it several times in recent days.

Thank you!

<br>

I did create a PR to add a basic hint in the README and inform users: #34
Please feel free to update/adjust as you see fit.
